@tool
class_name Chain
extends RoomResidentStatic

var wasCrateOriAttached := false
@export var attached_crate: Crate

const objName = "Chain"

## Should the chain continued to be destroyed after leaving the room?
@export var shouldDestructionPersist := false
# I'm just gonna assume that the chain and crate always reset cuz
# it's 2 am demmit and I want some sleep


# -----------------------------------------------------------------------------
# Extendable chain visuals
# -----------------------------------------------------------------------------

@export_category("Chain Visuals")

## Front-facing "O" chain-link sprite.
@export var chain_o_texture: Texture2D:
	set(value):
		chain_o_texture = value
		_request_chain_rebuild()

## Side-facing "I" chain-link sprite.
@export var chain_i_texture: Texture2D:
	set(value):
		chain_i_texture = value
		_request_chain_rebuild()

## Number of visual links in the chain.
@export_range(1, 200, 1) var link_count: int = 5:
	set(value):
		link_count = max(1, value)
		_request_chain_rebuild()

## Distance, in pixels, between the centres of consecutive links.
## Lower values make the sprites overlap more.
@export_range(1.0, 256.0, 1.0) var link_spacing: float = 28.0:
	set(value):
		link_spacing = max(1.0, value)
		_request_chain_rebuild()

## Uniform scale applied to every generated chain-link sprite.
@export_range(0.05, 10.0, 0.05) var link_scale: float = 1.0:
	set(value):
		link_scale = max(0.05, value)
		_request_chain_rebuild()

## Direction in which the chain grows from this node's origin.
## Examples: Vector2.DOWN, Vector2.UP, Vector2.LEFT, Vector2.RIGHT.
@export var chain_direction: Vector2 = Vector2.DOWN:
	set(value):
		chain_direction = value
		_request_chain_rebuild()

## Optional sideways offset for the "I" links. Useful for making the
## alternating O/I links look more naturally interlocked.
@export var vertical_offset: float = 0.0:
	set(value):
		vertical_offset = value
		_request_chain_rebuild()

## If enabled, O links are drawn above I links when they overlap.
@export var alternate_z_index: bool = true:
	set(value):
		alternate_z_index = value
		_request_chain_rebuild()

const GENERATED_CHAIN_ROOT := "__GeneratedChainVisuals"


func setup() -> void:
	roomResident = RoomResident.setup(objName, position)


func _ready() -> void:
	if attached_crate:
		attached_crate.attach(self)
		wasCrateOriAttached = true
	roomResident.isSafeToSnapshot = attached_crate and shouldDestructionPersist

	# Build the O/I visual links when the scene is loaded.
	rebuild_chain_visuals()


func onSlash(slashParams : Dictionary = {}, player : Player = null):
	if attached_crate:
		attached_crate.detach()
		attached_crate = null
		roomResident.isSafeToSnapshot = !shouldDestructionPersist
	queue_free()


static func constructObjectBySnapshot(snapshot : Dictionary,
	constructHandling : Callable) -> Chain:
	assert(snapshot["objectName"] == objName)
	var scene := load("uid://dr5hrvoct3vi0") as PackedScene
	var chain := scene.instantiate() as Chain
	chain.resync(snapshot)
	chain.shouldDestructionPersist = snapshot["shouldDestructionPersist"]
	chain.wasCrateOriAttached = snapshot["wasCrateOriAttached"]
	
	if snapshot["attachedCrate"] != null:
		chain.attached_crate = Crate.constructObjectBySnapshot(\
			snapshot["attachedCrate"], constructHandling)
		chain.attached_crate.z_index = chain.z_index + 1
	else:
		chain.attached_crate = null
	
	
	constructHandling.call(chain)
	return chain


func generateObjectSnapshot() -> Dictionary:
	var snapshot := super.generateObjectSnapshot()
	snapshot["objectName"] = objName
	snapshot["shouldDestructionPersist"] = shouldDestructionPersist
	snapshot["wasCrateOriAttached"] = wasCrateOriAttached

	if attached_crate != null:
		snapshot["attachedCrate"] = attached_crate.generateObjectSnapshot()
	else: 
		snapshot["attachedCrate"] = null
	return snapshot


func hasStateChanged() -> bool:
	return (wasCrateOriAttached and attached_crate == null) or \
		(!wasCrateOriAttached and attached_crate != null) #idk how this scenario occurs but eh


# -----------------------------------------------------------------------------
# Chain visual helper functions
# -----------------------------------------------------------------------------

## Rebuilds the visible chain using alternating O / I sprites.
func rebuild_chain_visuals() -> void:
	if not is_inside_tree():
		return

	var visual_root := _get_or_create_visual_root()

	# Only remove sprites generated by this system. This leaves all of the
	# chain scene's existing children completely untouched.
	for child in visual_root.get_children():
		visual_root.remove_child(child)
		child.queue_free()

	if chain_o_texture == null or chain_i_texture == null:
		return

	var direction := chain_direction
	if direction.is_zero_approx():
		direction = Vector2.DOWN
	direction = direction.normalized()

	# Perpendicular direction used for the optional I-link side offset.
	var perpendicular := Vector2(-direction.y, direction.x)

	for index in range(link_count):
		var link := Sprite2D.new()
		link.name = "ChainLink_%02d" % index

		var is_o_link := index % 2 == 0
		if is_o_link:
			link.texture = chain_o_texture
		else:
			link.texture = chain_i_texture

		var offset := direction * index * link_spacing 
		if not is_o_link:
			offset += perpendicular + Vector2(0, vertical_offset)

		link.position = offset + Vector2(0, -120)
		link.scale = Vector2.ONE * link_scale

		if alternate_z_index:
			link.z_index = 1 if is_o_link else 0

		visual_root.add_child(link)


## Adds visual links to the end of the chain.
func extend_chain(amount: int = 1) -> void:
	link_count += max(0, amount)


## Removes visual links from the end of the chain, but always keeps at least 1.
func shorten_chain(amount: int = 1) -> void:
	link_count = max(1, link_count - max(0, amount))


## Sets the chain length approximately in pixels.
func set_chain_length(length: float) -> void:
	link_count = max(1, int(ceil(max(0.0, length) / link_spacing)))


func _request_chain_rebuild() -> void:
	# Export setters can run before the node has entered the scene tree.
	# call_deferred also avoids rebuilding repeatedly in the middle of an
	# Inspector property update.
	if is_inside_tree():
		call_deferred("rebuild_chain_visuals")


func _get_or_create_visual_root() -> Node2D:
	var existing := get_node_or_null(GENERATED_CHAIN_ROOT) as Node2D
	if existing != null:
		return existing

	var visual_root := Node2D.new()
	visual_root.name = GENERATED_CHAIN_ROOT
	add_child(visual_root)

	# In editor mode, assigning an owner makes the generated holder visible in
	# the scene tree. Runtime-generated Sprite2Ds themselves do not need owners.
	if Engine.is_editor_hint() and owner != null:
		visual_root.owner = owner

	return visual_root
